builds:
  -
    binary: climanager
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: climanager
    homepage: https://github.com/darrenleak/climanager
    tap:
      owner: darrenleak
      name: climanager-tap 
    commit_author:
      name: darrenleak
      email: dleak22@gmail.com

checksum:
  name_template: "checksums.txt"