# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Climanager < Formula
  desc ""
  homepage "https://github.com/darrenleak/climanager"
  version "0.1.8"

  on_macos do
    url "https://github.com/darrenleak/climanager/releases/download/v0.1.8/climanager_0.1.8_darwin_all.tar.gz"
    sha256 "696ef0808a57484bce8421fe51fb733eb310894eac4b8e66d0d592cd8f7158d2"

    def install
      bin.install "climanager"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darrenleak/climanager/releases/download/v0.1.8/climanager_0.1.8_linux_arm64.tar.gz"
      sha256 "3351f7e691d86d82247c56c0fb85f9ef6b6637ff9c9951863045ec8ca220515c"

      def install
        bin.install "climanager"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/darrenleak/climanager/releases/download/v0.1.8/climanager_0.1.8_linux_amd64.tar.gz"
      sha256 "ff8d847b11604a996da0b18ab2cd52a2d15815d0416323e219657937318be8b9"

      def install
        bin.install "climanager"
      end
    end
  end
end
