name: Build bluff
on: 
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Build
        run: go build -o ./archive/bluff
      - uses: actions/upload-artifact@v3
        with:
          name: bluff
          path: ./artifact/bluff